apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-app
  namespace: jibin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp-app
  template:
    metadata:
      labels:
        app: gcp-app
    spec:
      containers:
        - name: gcp-app
          image: us-east1-docker.pkg.dev/traice-project/gcp-node-app-repo/gcp-node-app:latest
          ports:
            - containerPort: 80
