name: Deploy to GKE

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: traice-private-cluster
  CLUSTER_REGION: us-east1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use Artifact Registry
      run: |
        gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

    - name: Build and push Docker image
      run: |
        docker build -t us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcp-node-app-repo/gcp-node-app:$GITHUB_SHA .
        docker push us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcp-node-app-repo/gcp-node-app:$GITHUB_SHA

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME \
          --region $CLUSTER_REGION

    - name: Create namespace if not exists
      run: |
        kubectl get ns jibin || kubectl create ns jibin

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/

    - name: Force update with new image
      run: |
        kubectl set image deployment/gcp-node-app \
          gcp-node-app=us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcp-node-app-repo/gcp-node-app:$GITHUB_SHA \
          -n jibin || echo "Deployment not found — skipping rollout"

    - name: Show all resources in 'jibin' namespace
      run: |
        kubectl get all -n jibin
