name: Deploy to GKE

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: traice-private-cluster
  CLUSTER_REGION: us-east1-b
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcp-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push Docker image
      run: |
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME \
          --region $CLUSTER_REGION

    - name: Create namespace if not exists
      run: |
        kubectl get ns jibin || kubectl create ns jibin

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/

    - name: Show resources
      run: |
        kubectl get all -n jibin
